apiVersion: v1
kind: Service
metadata:
  name: employee-management-service
spec:
  type: LoadBalancer
  selector:
    app: employee-management-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000